---
title: "Values"
format: html
---

The values below guide our priorities and decision-making for all Scienceverse projects. 


1. **Quality Control**: The knowledge, data, code and software we create will be verified for accuracy, using publicly available methods and measures, such that users have enough context to interpret the results.

2. **Transparency**: We are committed to open source software and open access datasets for validation.

3. **AI Optional**: The use of generative AI will always be opt-in and transparently declared. We will prioritise non-AI functions where possible, and limit generative AI use to cases where it provides substantial benefits that cannot be realised with other methods.

4. **No Automated Evaluation**: While our software is designed to assist the evaluation of research, we will never support automated rankings or scoring.

5. **Data Privacy**: We will be fully transparent about what data we have access to and how those data will be used, as well as what will be shared with external services. Wherever possible, we will prioritise functions that share minimal data and services that have robust data protection. We will meet all EU data privacy regulations. 

6. **Accessibility**: We will provide our knowledge, data, code and software to all potential users with minimal barriers to access. We will prioritise access that is not unduly limited by wealth, disability or technical knowledge.

7. **Community Engagement**: Our work will reflect and respect the needs of a diverse range of research communities, and benefit their research practices. We are open to critique from the research community.

8. **Sustainability**: We are committed to the long-term viability of our work. We will actively protect and future-proof our work through technical maintenance, governance structures and strategic planning to make it a durable and relevant public good.

9. **Fair Recognition and Reward**: Contributions to knowledge, data, code, and software will be uniquely and persistently identified, and benefit a diverse range of contributors. 


These values are modified from the [values statement of the Research Transparency Check project](https://docs.google.com/document/d/1bbIkgUaiz3fpTXAeTF3h-gsfhqWEBN_n6OBcbFLfXjw), which partially funds the development of scienceverse projects metacheck and bibr.